var cache = [
    'build/index.html',
    'build/app/styles/bundle/lib.css',
    'build/app/styles/bundle/app.css',
    'build/app/scripts/lib.js',
    'build/app/scripts/app.js',
    'build/app/images/icons/png/menu62.png',
    'build/app/images/input_areas/images/clear.png',
    'build/app/images/input_areas/images/dialog.svg',
    'build/app/styles/bundle/drawer/images/ui/pattern.png',
    'build/app/styles/bundle/drawer/images/ui/header.png',
    'build/app/styles/bundle/drawer/images/ui/separator.png',
    'build/app/styles/bundle/drawer/images/ui/shadow_header.png',
    'build/app/styles/bundle/drawer/images/ui/pattern_subheader.png',
    'build/app/styles/bundle/drawer/images/ui/shadow.png',
    'build/app/styles/bundle/headers/images/icons/back.png',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Light.eot',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Light.otf',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Light.ttf',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Light.woff',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Bold.eot',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Bold.otf',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Bold.ttf',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Bold.woff',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Regular.eot',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Regular.otf',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Regular.ttf',
    'build/app/styles/bundle/fonts/FiraSans/FiraSans-Regular.woff',
    'build/app/styles/bundle/input_areas/images/clear.png',
    'build/app/styles/bundle/input_areas/images/dialog.svg',
    'build/app/styles/bundle/switches/images/switch/background_off.png',
    'build/app/styles/bundle/status/images/ui/pattern.png'
];

module.exports = cache; 